name: Deploy

on:
  push:

jobs:
  deploy:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thomasjeanlouis1/proxy:${{ github.ref_name }}_${{ github.run_number }}

      # Update gameserver docker image tag
      # - run: >
      #     curl -L
      #     -X PATCH
      #     -H "Accept: application/vnd.github+json"
      #     -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}"
      #     -H "X-GitHub-Api-Version: 2022-11-28"
      #     https://api.github.com/repos/thomasjean-louis/infra/environments/${{ github.ref_name }}/variables/PROXY_SERVER_DOCKER_IMAGE
      #     -d '{"name":"PROXY_SERVER_DOCKER_IMAGE","value":"${{ github.ref_name }}_${{ github.run_number }}"}'

      # Launch infra workflow, to update proxy image used
      # - run: >
      #     curl -L
      #     -X POST
      #     -H "Accept: application/vnd.github+json"
      #     -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}"
      #     -H "X-GitHub-Api-Version: 2022-11-28"
      #     https://api.github.com/repos/thomasjean-louis/infra/actions/workflows/main.yml/dispatches
      #     -d '{"ref":"${{ github.ref_name }}"}'
